# Generated by Django 3.2.8 on 2021-10-18 11:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField()),
                ('description', ckeditor.fields.RichTextField()),
                ('ifSubmitted', models.BooleanField()),
                ('ifopened', models.BooleanField()),
                ('ifClosed', models.BooleanField()),
                ('totalMarks', models.FloatField()),
                ('percentageTowardsCourseTotal', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSubmitted', models.DateTimeField()),
                ('submission', models.FileField(upload_to='')),
                ('reviewedFile', models.FileField(upload_to='')),
                ('forAssign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.assignment')),
                ('fromStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('marks', models.FloatField()),
                ('forSubmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.submissions')),
            ],
        ),
    ]
