# Generated by Django 3.2.8 on 2021-10-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20211019_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='ifSubmitted',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='ifopened',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course.course'),
        ),
    ]
