# Generated by Django 3.2.8 on 2021-10-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20211019_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='reviewedFile',
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submission',
            field=models.FileField(upload_to='abc/'),
        ),
    ]
